# Generated by Django 3.0.4 on 2020-05-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatmessages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
