# Generated by Django 3.0.4 on 2020-05-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatmessages', '0003_auto_20200430_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='created_at_format',
            field=models.CharField(default='ppppppp', max_length=20),
            preserve_default=False,
        ),
    ]
